const FOUNDATION_TABLES = [
  'roles', 'user_roles', 'audit_events', 'secrets', 'secret_versions',
  'channels', 'channel_credentials', 'channel_sessions', 'webhook_events',
  'teams', 'team_members', 'queues', 'queue_members', 'tags', 'conversation_tags',
  'sla_policies', 'conversation_sla', 'routing_rules', 'templates', 'template_versions',
  'outbox_jobs', 'delivery_events', 'failed_jobs', 'conversation_assignments', 'internal_notes',
  'automation_rules', 'automation_runs', 'privacy_requests', 'retention_runs', 'metrics_rollups',
];

function foundationMigration() {
  return `
    create table if not exists roles (name text primary key check (name in ('admin','manager','agent','viewer')), description text not null default '');
    create table if not exists user_roles (user_id text not null references users(id) on delete cascade, role_name text not null references roles(name), assigned_at timestamptz not null default now(), assigned_by text references users(id) on delete set null, primary key(user_id, role_name));
    create table if not exists audit_events (id uuid primary key, actor_user_id text references users(id) on delete set null, action text not null, resource_type text not null, resource_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
    create table if not exists secrets (id uuid primary key, purpose text not null unique, active_version_id uuid, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    create table if not exists secret_versions (id uuid primary key, secret_id uuid not null references secrets(id) on delete cascade, ciphertext text not null, key_version integer not null default 1, created_at timestamptz not null default now(), retired_at timestamptz, created_by text references users(id) on delete set null);
    do $$ begin
      if not exists (select 1 from pg_constraint where conname = 'secrets_active_version_fk' and conrelid = 'secrets'::regclass) then
        alter table secrets add constraint secrets_active_version_fk foreign key(active_version_id) references secret_versions(id) deferrable initially deferred;
      end if;
    end $$;
    create table if not exists channels (id uuid primary key, provider text not null check(provider in ('waha','meta')), name text not null, enabled boolean not null default true, config jsonb not null default '{}'::jsonb, created_by text references users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(provider,name));
    create table if not exists channel_credentials (channel_id uuid primary key references channels(id) on delete cascade, secret_id uuid not null references secrets(id), validated_at timestamptz, validation_state text not null default 'unconfigured' check(validation_state in ('unconfigured','valid','invalid','error')), last_error text, updated_at timestamptz not null default now());
    create table if not exists channel_sessions (id uuid primary key, channel_id uuid not null references channels(id) on delete cascade, provider_session_id text, state text not null default 'new', qr_payload text, qr_expires_at timestamptz, last_seen_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(channel_id, provider_session_id));
    create table if not exists webhook_events (id uuid primary key, channel_id uuid not null references channels(id) on delete cascade, provider_event_id text not null, event_type text not null, signature_valid boolean not null, payload jsonb not null, status text not null default 'pending' check(status in ('pending','processing','processed','failed','dead_letter')), attempts integer not null default 0 check(attempts >= 0), max_attempts integer not null default 8 check(max_attempts > 0), available_at timestamptz not null default now(), locked_at timestamptz, locked_by text, lease_token uuid, received_at timestamptz not null default now(), processed_at timestamptz, processing_error text, updated_at timestamptz not null default now(), unique (channel_id, provider_event_id));
    alter table webhook_events add column if not exists status text not null default 'pending';
    alter table webhook_events add column if not exists attempts integer not null default 0;
    alter table webhook_events add column if not exists max_attempts integer not null default 8;
    alter table webhook_events add column if not exists available_at timestamptz not null default now();
    alter table webhook_events add column if not exists locked_at timestamptz;
    alter table webhook_events add column if not exists locked_by text;
    alter table webhook_events add column if not exists lease_token uuid;
    alter table webhook_events add column if not exists updated_at timestamptz not null default now();
    alter table webhook_events drop constraint if exists webhook_events_status_check;
    alter table webhook_events add constraint webhook_events_status_check check(status in ('pending','processing','processed','failed','dead_letter')) not valid;
    create index if not exists webhook_events_ready_idx on webhook_events(status, available_at) where status in ('pending','failed');
    create table if not exists teams (id uuid primary key, name text not null unique, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    create table if not exists team_members (team_id uuid not null references teams(id) on delete cascade, user_id text not null references users(id) on delete cascade, capacity integer not null default 10 check(capacity > 0), active boolean not null default true, primary key(team_id,user_id));
    create table if not exists queues (id uuid primary key, name text not null unique, team_id uuid references teams(id) on delete set null, active boolean not null default true, strategy text not null default 'round_robin' check(strategy in ('round_robin','least_open','manual')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    create table if not exists queue_members (queue_id uuid not null references queues(id) on delete cascade, user_id text not null references users(id) on delete cascade, priority integer not null default 0, active boolean not null default true, primary key(queue_id,user_id));
    create table if not exists tags (id uuid primary key, name text not null unique, color text not null default '#506d48', created_at timestamptz not null default now(), check(color ~ '^#[0-9a-fA-F]{6}$'));
    create table if not exists conversation_tags (conversation_id text not null references conversations(id) on delete cascade, tag_id uuid not null references tags(id) on delete cascade, created_at timestamptz not null default now(), primary key(conversation_id,tag_id));
    create table if not exists sla_policies (id uuid primary key, name text not null unique, first_response_seconds integer not null check(first_response_seconds > 0), resolution_seconds integer not null check(resolution_seconds > 0), active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    create table if not exists conversation_sla (conversation_id text primary key references conversations(id) on delete cascade, policy_id uuid not null references sla_policies(id), first_response_due_at timestamptz not null, resolution_due_at timestamptz not null, first_response_at timestamptz, breached_at timestamptz);
    create table if not exists routing_rules (id uuid primary key, name text not null unique, priority integer not null default 100, active boolean not null default true, matchers jsonb not null default '{}'::jsonb, target_queue_id uuid references queues(id) on delete set null, target_team_id uuid references teams(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    create table if not exists templates (id uuid primary key, channel_id uuid references channels(id) on delete set null, name text not null, language text not null default 'pt_BR', status text not null default 'draft' check(status in ('draft','approved','rejected','disabled')), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(channel_id,name,language));
    create table if not exists template_versions (id uuid primary key, template_id uuid not null references templates(id) on delete cascade, body text not null, variables jsonb not null default '[]'::jsonb, provider_template_id text, version integer not null, created_at timestamptz not null default now(), unique(template_id,version));
    create table if not exists outbox_jobs (id uuid primary key, channel_id uuid references channels(id) on delete set null, conversation_id text references conversations(id) on delete set null, kind text not null check(kind in ('text','template')), payload jsonb not null, idempotency_key text not null unique, status text not null default 'pending' check(status in ('pending','processing','sent','failed','dead_letter','delivery_unknown')), attempts integer not null default 0 check(attempts >= 0), max_attempts integer not null default 8 check(max_attempts > 0), available_at timestamptz not null default now(), locked_at timestamptz, locked_by text, lease_token uuid, provider_message_id text, last_error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    alter table outbox_jobs add column if not exists lease_token uuid;
    alter table outbox_jobs drop constraint if exists outbox_jobs_status_check;
    alter table outbox_jobs add constraint outbox_jobs_status_check check(status in ('pending','processing','sent','failed','dead_letter','delivery_unknown')) not valid;
    create index if not exists outbox_jobs_ready_idx on outbox_jobs(status, available_at) where status in ('pending','failed');
    create table if not exists delivery_events (id uuid primary key, channel_id uuid references channels(id) on delete set null, message_id text references conversation_messages(id) on delete cascade, provider_message_id text not null, status text not null check(status in ('queued','sent','delivered','read','failed')), occurred_at timestamptz not null, payload jsonb not null default '{}'::jsonb, unique(channel_id, provider_message_id, status));
    create table if not exists failed_jobs (id uuid primary key, outbox_job_id uuid not null unique references outbox_jobs(id) on delete cascade, reason text not null, payload jsonb not null, failed_at timestamptz not null default now(), resolved_at timestamptz, resolved_by text references users(id) on delete set null);
    alter table conversations add column if not exists assigned_user_id text references users(id) on delete set null;
    alter table conversations add column if not exists queue_id uuid references queues(id) on delete set null;
    alter table conversations add column if not exists priority text not null default 'normal' check(priority in ('low','normal','high','urgent'));
    alter table conversations add column if not exists last_inbound_at timestamptz;
    create index if not exists conversations_assignee_idx on conversations(assigned_user_id, status, last_message_at desc);
    create table if not exists conversation_assignments (id uuid primary key, conversation_id text not null references conversations(id) on delete cascade, assigned_user_id text references users(id) on delete set null, assigned_by text references users(id) on delete set null, queue_id uuid references queues(id) on delete set null, reason text not null default 'manual', created_at timestamptz not null default now());
    create table if not exists internal_notes (id uuid primary key, conversation_id text not null references conversations(id) on delete cascade, body text not null check(char_length(body) between 1 and 4000), created_by text references users(id) on delete set null, created_at timestamptz not null default now());
    create table if not exists automation_rules (id uuid primary key, name text not null unique, trigger_type text not null, conditions jsonb not null default '{}'::jsonb, actions jsonb not null default '[]'::jsonb, active boolean not null default false, version integer not null default 1, created_by text references users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
    create table if not exists automation_runs (id uuid primary key, rule_id uuid not null references automation_rules(id) on delete cascade, conversation_id text references conversations(id) on delete set null, status text not null check(status in ('pending','simulated','completed','failed','skipped')), result jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), completed_at timestamptz);
    create table if not exists privacy_requests (id uuid primary key, contact_phone text not null, kind text not null check(kind in ('export','anonymize','delete')), status text not null default 'open' check(status in ('open','processing','completed','rejected')), requested_by text references users(id) on delete set null, result jsonb not null default '{}'::jsonb, expires_at timestamptz, created_at timestamptz not null default now(), completed_at timestamptz);
    create table if not exists retention_runs (id uuid primary key, policy_name text not null, status text not null check(status in ('started','completed','failed')), deleted_count integer not null default 0, details jsonb not null default '{}'::jsonb, started_at timestamptz not null default now(), completed_at timestamptz);
    create table if not exists metrics_rollups (bucket_start timestamptz not null, bucket_kind text not null check(bucket_kind in ('hour','day')), channel_id uuid references channels(id) on delete set null, queue_id uuid references queues(id) on delete set null, inbound_count integer not null default 0, outbound_count integer not null default 0, delivered_count integer not null default 0, read_count integer not null default 0, failed_count integer not null default 0, open_count integer not null default 0, breached_count integer not null default 0, primary key(bucket_start,bucket_kind,channel_id,queue_id));
  `;
}

module.exports = { FOUNDATION_TABLES, foundationMigration };