function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char]);
}
function csrfInput(token) { return token ? `<input type="hidden" name="csrf_token" value="${esc(token)}">` : ''; }
function navItem(id, label, active, href = `/${id}`) { return `<a class="nav-item${active === id ? ' active' : ''}"${active === id ? ' aria-current="page"' : ''} href="${href}">${esc(label)}</a>`; }
function deliveryLabel(status) { return ({ queued:'Na fila', sending:'Enviando', sent:'Enviada', delivered:'Entregue', read:'Lida', failed:'Falhou' })[status] || ''; }
function primaryNav(active) { return `${navItem('inbox','Central',active,'/inbox')}${navItem('connections','Canais e Conexões',active,'/connections')}${navItem('contacts','Contatos',active,'/contacts')}${navItem('leads','Leads',active,'/leads')}${navItem('settings','Configurações',active,'/settings/channels')}`; }
function sidebar(active) {
  return `<aside class="sidebar" aria-label="Navegação principal"><a class="brand" href="/inbox" aria-label="CRMTSiAPP, ir para Central"><span class="brand-mark" aria-hidden="true">C</span><span>CRMTSiAPP</span></a><div class="workspace-label">TSi Telecom</div><nav id="primary-navigation">${primaryNav(active)}</nav><div class="sidebar-footer">Operação local segura</div></aside><details class="mobile-navigation"><summary aria-label="Abrir navegação principal"><span class="brand-mark" aria-hidden="true">C</span><span>Menu</span></summary><nav aria-label="Navegação principal móvel">${primaryNav(active)}</nav></details>`;
}
function settingsNav(active) {
  const items = [['channels','Canais e API'],['team','Equipe e permissões'],['queues','Filas e SLA'],['templates','Templates'],['automation','Automações'],['privacy','Dados e privacidade'],['appearance','Aparência'],['catalog','Parâmetros avançados']];
  return `<nav class="settings-nav" aria-label="Seções de configurações">${items.map(([id,label]) => `<a class="settings-nav-item${active === id ? ' active' : ''}"${active === id ? ' aria-current="page"' : ''} href="/settings/${id}">${label}</a>`).join('')}</nav>`;
}
function objectList(rows, primary, secondary, empty) {
  return rows?.length ? `<ul class="object-list">${rows.map(row => `<li><strong>${esc(primary(row))}</strong><span>${esc(secondary(row))}</span></li>`).join('')}</ul>` : `<div class="empty-list"><strong>${esc(empty)}</strong><span>Configure este domínio sem impedir a operação local.</span></div>`;
}
function renderConnections(state) {
  const channels = Array.isArray(state.channels) && state.channels.length ? state.channels : (state.configured ? [{ id:'legacy', provider:'waha', name:'WhatsApp', session_name:state.sessionName, validation_state: state.connected ? 'valid' : 'pending', last_error:state.healthError }] : []);
  const cards = channels.length ? channels.map(c => `<article class="panel channel-card"><div class="card-title"><div><p class="eyebrow">${esc(c.provider)}</p><h2>Canal parceiro · ${esc(c.name)}</h2></div><span class="status ${c.validation_state === 'valid' ? 'online' : 'pending'}">${esc(c.validation_state === 'valid' ? 'WhatsApp conectado · Conexão validada' : c.validation_state === 'error' ? 'Teste indisponível' : 'Aguardando conexão')}</span></div><dl><div><dt>Sessão</dt><dd>${esc(c.session_name || 'Não definida')}</dd></div><div><dt>Última validação</dt><dd>${esc(c.validated_at ? new Date(c.validated_at).toLocaleString('pt-BR') : 'Nunca')}</dd></div></dl><div class="card-actions"><a class="button" href="/settings/channels#${esc(c.id)}">Gerenciar</a><a class="button" href="/settings/channels#${esc(c.id)}">Testar conexão</a></div>${c.last_error ? `<p class="hint error-hint">${esc(c.last_error)}</p>` : ''}</article>`).join('') : `<article class="panel empty-card"><h2>Canal parceiro · WhatsApp</h2><p>Cadastre WAHA ou Meta Cloud API. A Central continua disponível enquanto a integração estiver sem credenciais.</p><a class="button primary" href="/settings/channels">Cadastrar canal</a></article>`;
  return `<header class="page-header"><div><p class="eyebrow">CANAIS</p><h1>Conexões</h1><p>Estado real de cada canal, sem expor tokens nem afirmar conectividade sem teste.</p></div><a class="button primary" href="/settings/channels">Novo canal</a></header><section class="connection-grid">${cards}</section>`;
}
function settingsPanel(section, state) {
  const csrf = csrfInput(state.csrfToken);
  if (section === 'channels') return `<section class="panel settings-panel"><p class="eyebrow">CANAIS</p><h2>Canal WhatsApp</h2><p>Escolha um provedor e preencha somente seu bloco. Segredos ficam cifrados no servidor e nunca são reexibidos.</p><form method="post" action="/settings/channels" class="form-grid">${csrf}<label>Nome do canal<input name="name" required maxlength="100" placeholder="Atendimento principal"></label><label>Provedor de canal<select name="provider"><option value="waha">WAHA compatível</option><option value="meta">Meta Cloud API</option></select></label><fieldset class="span-2"><legend>Configuração WAHA</legend><label>URL da API WAHA<input name="base_url" maxlength="300" placeholder="https://waha.exemplo"></label><label>Sessão WAHA<input name="session_name" maxlength="160" placeholder="tsi-atendimento"></label><label>Chave da API WAHA<input name="access_token" type="password" autocomplete="off"></label><label>Segredo de webhook WAHA<input name="webhook_secret" type="password" autocomplete="off"></label></fieldset><fieldset class="span-2"><legend>Configuração Meta Cloud API</legend><label>Versão Graph API<input name="graph_version" maxlength="20" placeholder="v22.0"></label><label>WABA ID<input name="waba_id" maxlength="80" placeholder="ID da conta do WhatsApp Business"></label><label>Phone Number ID<input name="phone_number_id" maxlength="160" placeholder="ID do número"></label><label>Token de acesso Meta<input name="meta_access_token" type="password" autocomplete="off"></label><label>App Secret Meta<input name="meta_app_secret" type="password" autocomplete="off"></label><label>Verify token Meta<input name="verify_token" type="password" autocomplete="off"></label><p class="hint">Compatibilidade atual: ao selecionar Meta, o servidor ainda lê <em>base_url</em> como versão Graph e <em>session_name</em> como Phone Number ID. A API de criação precisa aceitar <code>graph_version</code>, <code>waba_id</code> e <code>phone_number_id</code> para concluir esta migração.</p></fieldset><div class="form-actions"><button class="button primary" type="submit">Criar canal e salvar configuração</button><p class="hint">O estado permanece “não configurado” até existir uma rota de teste real. Não afirmamos conectividade sem probe.</p></div></form></section>`;
  if (section === 'team') return `<section class="panel settings-panel"><p class="eyebrow">EQUIPE</p><h2>Equipe e permissões</h2><p>Crie equipes e defina capacidade por atendente. Papéis são aplicados no servidor.</p><form method="post" action="/settings/team" class="inline-form">${csrf}<label>Nome da equipe<input name="name" required maxlength="100" placeholder="Suporte"></label><button class="button primary">Criar equipe</button></form>${objectList(state.teams, x => x.name, x => `${x.member_count || 0} membro(s)`, 'Nenhuma equipe')}</section>`;
  if (section === 'queues') return `<section class="panel settings-panel"><p class="eyebrow">DISTRIBUIÇÃO</p><h2>Filas e SLA</h2><p>Filas orientam responsabilidade e prioridade; o SLA dá visibilidade antes do vencimento.</p><form method="post" action="/settings/queues" class="form-grid">${csrf}<label>Nome da fila<input name="name" required maxlength="100" placeholder="Atendimento geral"></label><label>Estratégia<select name="strategy"><option value="manual">Manual</option><option value="round_robin">Round-robin</option><option value="least_open">Menor carga</option></select></label><div class="form-actions"><button class="button primary">Criar fila</button></div></form>${objectList(state.queues, x => x.name, x => x.strategy, 'Nenhuma fila')}</section>`;
  if (section === 'templates') return `<section class="panel settings-panel"><p class="eyebrow">MENSAGENS</p><h2>Templates</h2><p>Use template aprovado fora da janela de atendimento. O status sempre é explícito.</p><form method="post" action="/settings/templates" class="form-grid">${csrf}<label>Nome<input name="name" required maxlength="128" placeholder="retorno_inicial"></label><label>Idioma<input name="language" value="pt_BR" required maxlength="12"></label><label class="span-2">Conteúdo<textarea name="body" required maxlength="4000" placeholder="Olá {{1}}, como podemos ajudar?"></textarea></label><div class="form-actions"><button class="button primary">Salvar como rascunho</button></div></form>${objectList(state.templates, x => x.name, x => `${x.language} · ${x.status}`, 'Nenhum template')}</section>`;
  const labels = { automation:['AUTOMAÇÃO','Automações auditáveis','Regras devem ser revisáveis e auditadas. Nenhuma automação envia sem política de canal.'], privacy:['LGPD','Dados e privacidade','Solicitações de exportação, exclusão e retenção terão expiração e auditoria explícitas.'], appearance:['APARÊNCIA','Identidade da operação','Tokens priorizam clareza operacional, contraste e foco visível.'] };
  const [eyebrow, title, text] = labels[section] || labels.appearance;
  return `<section class="panel settings-panel"><p class="eyebrow">${eyebrow}</p><h2>${title}</h2><p>${text}</p><div class="empty-list"><strong>Nenhum objeto ativo</strong><span>Este workspace será populado por dados persistidos, não por parâmetros fictícios.</span></div></section>`;
}
function renderSettings(section, state) { return `<header class="page-header"><div><p class="eyebrow">CONFIGURAÇÕES</p><h1>Configurações</h1><p>Workspaces executáveis para operação, não um catálogo de chaves.</p></div></header><div class="settings-layout">${settingsNav(section)}<section class="settings-content" aria-label="Conteúdo de configurações">${settingsPanel(section, state)}</section></div>`; }
function renderCrm(kind, state) {
  const contacts = kind === 'contacts'; const rows = state[kind] || []; const csrf = csrfInput(state.csrfToken);
  const form = contacts ? `<label>Nome<input name="name" required maxlength="200"></label><label>Telefone<input name="phone" maxlength="80"></label><label>E-mail<input name="email" type="email" maxlength="320"></label>` : `<label>Título<input name="title" required maxlength="200"></label><label>Origem<input name="source" maxlength="120"></label><label>Valor (centavos)<input name="value_cents" type="number" min="0" value="0"></label>`;
  return `<header class="page-header"><div><p class="eyebrow">CRM</p><h1>${contacts ? 'Contatos' : 'Leads'}</h1><p>Dados persistidos localmente e conectados à Central.</p></div></header><section class="panel settings-panel"><form method="post" action="/${kind}" class="form-grid">${csrf}${form}<div class="form-actions"><button class="button primary">Criar ${contacts ? 'contato' : 'lead'}</button></div></form>${objectList(rows, x => x.name || x.title, x => x.phone || x.email || x.status || x.source || 'Sem detalhes', contacts ? 'Nenhum contato' : 'Nenhum lead')}</section>`;
}
function renderInbox(state) {
  const conversations = Array.isArray(state.conversations) ? state.conversations : []; const selected = state.selectedConversation || null; const csrf = csrfInput(state.csrfToken); const filter = state.filter === 'closed' ? 'closed' : state.filter === 'open' ? 'open' : 'all'; const scope = state.scope || 'all';
  const tabs = [['open','Fila','/inbox?filter=open'],['mine','Minhas','/inbox?scope=mine'],['all','Todos','/inbox'],['closed','Fechadas','/inbox?filter=closed']].map(([id,label,href]) => `<a class="inbox-tab${scope === id || (id === 'open' && filter === 'open') || (id === 'closed' && filter === 'closed') ? ' active' : ''}" href="${href}">${label}</a>`).join('');
  const rows = conversations.length ? conversations.map(c => { const conversationHref = `/inbox/${encodeURIComponent(c.id)}${scope === 'mine' ? '?scope=mine' : filter !== 'all' ? `?filter=${encodeURIComponent(filter)}` : ''}`; return `<a class="conversation${selected?.id === c.id ? ' selected' : ''}" href="${conversationHref}"><span class="avatar">${esc(String(c.name || '?').slice(0,1).toUpperCase())}</span><span class="conversation-copy"><strong>${esc(c.name)}</strong><small>${esc(c.preview || 'Sem mensagens')}</small><em>${esc(c.queue_name || 'Sem fila')}${c.assignee_name ? ` · ${esc(c.assignee_name)}` : ''}</em></span>${Number(c.unread_count || 0) ? `<b class="unread">${Number(c.unread_count)}</b>` : ''}</a>`; }).join('') : `<div class="empty-list" role="status"><strong>Nenhuma conversa nesta visão</strong><span>Conecte um canal ou inicie uma conversa local.</span></div>`;
  const messages = (state.messages || []).map(m => `<div class="message ${m.direction === 'outbound' ? 'outbound' : 'inbound'}"><p>${esc(m.body)}</p><small>${esc(m.created_at ? new Date(m.created_at).toLocaleString('pt-BR') : '')}${m.delivery_status ? ` · <span class="delivery">${esc(deliveryLabel(m.delivery_status))}</span>` : ''}</small></div>`).join('');
  const serviceWindow = state.customerServiceWindow; const metaWindowExpired = selected?.channel_provider === 'meta' && serviceWindow && !serviceWindow.open;
  const windowNotice = selected?.channel_provider === 'meta' ? (metaWindowExpired ? `<p class="window-notice expired" role="status"><strong>A janela de atendimento Meta expirou.</strong> Envie um template aprovado para retomar o contato.</p>` : `<p class="window-notice"><strong>Envio livre disponível até</strong> ${esc(serviceWindow?.expiresAt ? new Date(serviceWindow.expiresAt).toLocaleString('pt-BR') : 'o próximo evento de canal')}.</p>`) : '';
  const templateRecovery = (() => { const templates = state.approvedTemplates || []; if (!metaWindowExpired) return ''; if (!templates.length) return `<div class="composer composer-blocked" role="status"><p><strong>Nenhum template aprovado disponível.</strong> Cadastre/sincronize um template Meta aprovado para retomar este contato.</p><a class="button" href="/settings/templates">Gerenciar templates</a></div>`; return `<form class="composer template-composer" method="post" action="/inbox/${encodeURIComponent(selected.id)}/templates">${csrf}<label>Template aprovado<select name="template_id" required>${templates.map(template => `<option value="${esc(template.id)}">${esc(template.name)} · ${esc(template.language)}</option>`).join('')}</select></label><label>Variáveis (uma por linha)<textarea name="variables" maxlength="4000" placeholder="Preencha somente as variáveis exigidas pelo template"></textarea></label><button class="button primary" type="submit">Enviar template aprovado</button></form>`; })();
  const composer = !selected ? '' : metaWindowExpired ? templateRecovery : `<form class="composer" method="post" action="/inbox/${encodeURIComponent(selected.id)}/messages">${csrf}<textarea name="body" required maxlength="4000" placeholder="Escreva uma mensagem" aria-label="Mensagem"></textarea><button class="button primary" type="submit">Enviar mensagem</button></form>`;
  const thread = selected ? `<section class="thread" aria-label="Conversa selecionada"><header class="thread-header"><div><h2>${esc(selected.contact_name)}</h2><p>${esc(selected.contact_phone || 'Sem telefone')}</p>${windowNotice}</div><div class="thread-actions"><span class="status ${selected.status === 'closed' ? 'pending' : 'online'}">${selected.status === 'closed' ? 'Fechada' : 'Aberta'}</span><form method="post" action="/inbox/${encodeURIComponent(selected.id)}/status">${csrf}<input type="hidden" name="status" value="${selected.status === 'closed' ? 'open' : 'closed'}"><button type="submit">${selected.status === 'closed' ? 'Reabrir conversa' : 'Fechar conversa'}</button></form></div></header><div class="messages" aria-live="polite">${messages || '<div class="empty-list" role="status"><strong>Sem mensagens</strong><span>Envie a primeira resposta quando o canal estiver pronto.</span></div>'}</div>${composer}</section>` : `<section class="thread-empty" aria-label="Conversa selecionada"><div class="empty-illustration" aria-hidden="true">⌁</div><h2>Selecione uma conversa</h2><p>Acompanhe mensagens, entrega, responsável e contexto do cliente.</p><a class="button primary" href="/connections">Conecte um canal</a></section>`;
  const assignmentForm = selected ? `<form class="assignment-form" method="post" action="/inbox/${encodeURIComponent(selected.id)}/assignment">${csrf}<label>Fila<select name="queue_id"><option value="">Sem fila</option>${(state.queues || []).map(queue => `<option value="${esc(queue.id)}"${selected.queue_id === queue.id ? ' selected' : ''}>${esc(queue.name)}</option>`).join('')}</select></label><label>Responsável<select name="assigned_user_id"><option value="">Não atribuído</option>${(state.assignableUsers || []).map(agent => `<option value="${esc(agent.id)}"${selected.assigned_user_id === agent.id ? ' selected' : ''}>${esc(agent.name)}</option>`).join('')}</select></label><button type="submit">Salvar atribuição</button></form>` : '';
  const context = selected ? `<aside class="contact-panel" aria-label="Contexto do contato"><p class="eyebrow">CONTATO</p><h3>${esc(selected.contact_name)}</h3><p>${esc(selected.contact_phone || 'Sem telefone')}</p><dl><div><dt>Fila</dt><dd>${esc(selected.queue_name || 'Não atribuída')}</dd></div><div><dt>Responsável</dt><dd>${esc(selected.assignee_name || 'Não atribuído')}</dd></div></dl>${assignmentForm}<section><h4>Notas internas</h4><p class="hint">Notas, atividades e auditoria permanecem internas.</p></section></aside>` : `<aside class="contact-panel" aria-label="Contexto do contato"><p class="eyebrow">CONTEXTO</p><h3>Sem conversa selecionada</h3><p>Perfil, etiquetas, atividades e notas internas aparecem aqui.</p></aside>`;
  return `<header class="page-header compact"><div><p class="eyebrow">CENTRAL</p><h1>Conversas</h1></div><div class="header-actions"><a class="button" href="/connections">Canais</a><a class="button primary" href="#nova-conversa">Nova conversa</a></div></header><section class="inbox-layout"><aside class="conversation-list" aria-label="Lista de conversas"><nav class="inbox-tabs" aria-label="Visões da Central">${tabs}</nav><form class="inbox-filters" method="get" action="/inbox"><input name="q" value="${esc(state.query || '')}" placeholder="Buscar conversa" aria-label="Buscar conversa"><label class="sr-only" for="conversation-filter">Estado da conversa</label><select id="conversation-filter" name="filter"><option value="all"${filter === 'all' ? ' selected' : ''}>Todas</option><option value="open"${filter === 'open' ? ' selected' : ''}>Abertas</option><option value="closed"${filter === 'closed' ? ' selected' : ''}>Fechadas</option></select><button type="submit">Filtrar</button></form>${rows}<form id="nova-conversa" class="new-conversation" method="post" action="/inbox">${csrf}<label>Nome do contato<input name="contact_name" required maxlength="200"></label><label>Telefone<input name="contact_phone" maxlength="80"></label><button class="button primary" type="submit">Nova conversa</button></form></aside>${thread}${context}</section>`;
}
function renderWorkspace(view, state = {}) {
  const active = view.startsWith('settings') ? 'settings' : view; let body;
  if (view === 'connections') body = renderConnections(state); else if (view === 'contacts' || view === 'leads') body = renderCrm(view, state); else if (view.startsWith('settings/')) body = renderSettings(view.slice(9), state); else if (view === 'settings') body = renderSettings('channels', state); else body = renderInbox(state);
  return `<div class="workspace">${sidebar(active)}<main class="workspace-main">${body}</main></div>`;
}
module.exports = { deliveryLabel, renderWorkspace };
