const { escapeHtml } = require('./content-compiler');

function renderCampaignEditor({ draft = {}, errors = [], csrfToken = '' } = {}) {
  const content = draft.content || { blocks: [] };
  const blocks = content.blocks || [];
  const errorRows = errors.map(error => `<li>${escapeHtml(error.blockId || 'Conteúdo')}: ${escapeHtml(error.code || error)}</li>`).join('');
  const blockRows = blocks.map((block, index) => `<li data-block-index="${index}" tabindex="0"><strong>${escapeHtml(block.type)}</strong><span>${escapeHtml(block.text || '')}</span><button type="button" data-action="move-up" aria-label="Mover bloco ${index + 1} para cima">↑</button><button type="button" data-action="move-down" aria-label="Mover bloco ${index + 1} para baixo">↓</button><button type="button" data-action="remove" aria-label="Remover bloco ${index + 1}">Remover</button></li>`).join('');
  return `<section class="visual-editor campaign-editor" aria-labelledby="campaign-editor-title"><header><h1 id="campaign-editor-title">Editor de Campanha</h1><p>Use blocos allowlisted. Variáveis: {{contact.name}}, {{contact.id}}, {{contact.phone}}, {{company.name}}.</p></header><div id="campaign-editor-status" role="status" aria-live="polite"></div><form id="campaign-editor-form"><input type="hidden" name="csrf_token" value="${escapeHtml(csrfToken)}"><label>Nome<input name="name" value="${escapeHtml(draft.name || '')}" required maxlength="160"></label><label>Canal<select name="channel"><option value="waha" ${draft.channel === 'waha' ? 'selected' : ''}>WAHA</option><option value="meta" ${draft.channel === 'meta' ? 'selected' : ''}>Meta</option></select></label><section aria-label="Blocos de conteúdo"><h2>Blocos</h2><ol id="campaign-block-list">${blockRows || '<li>Nenhum bloco</li>'}</ol><div class="form-actions"><button type="button" data-add-block="paragraph">Adicionar texto</button><button type="button" data-add-block="button">Adicionar botão</button><button type="button" data-add-block="image">Adicionar imagem</button></div></section><section aria-label="Erros"><h2>Erros</h2><ul id="campaign-errors" aria-live="assertive">${errorRows || '<li>Sem erros</li>'}</ul></section><div class="form-actions"><button type="button" data-action="preview">Preview</button><button type="button" data-action="publish">Publicar</button><button type="button" data-action="restore">Restaurar versão</button></div></form></section>`;
}

module.exports = { renderCampaignEditor };